src/Entity/Structure.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\StructureRepository;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=StructureRepository::class)
 * @Vich\Uploadable
 */
class Structure
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $organization_type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
	 * @Assert\Choice(
	 *{"Ecole maternelle", "Ecole primaire", "Collège", "Lycée"},
	 *message = "Le choix {{ value }} est invalide."
	 *)
     */
    private $school_type;

    /**
     * @ORM\Column(type="string", length=255)
	 * @Assert\NotBlank(message="Erreur. Ce champ est obligatoire.") 
     */
    private $name;

   /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="structure", fileNameProperty="logoName")
     * 
     * @var File|null
     */
    private $logoFile;

    /**
     * @ORM\Column(type="string", nullable=true)
     *
     * @var string|null
     */
    private $logoName;

     /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     */
    private $updateAt;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $summar;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postaladdress;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
	 * @Assert\Email(
     *     message = "L'adresse email {{ value }} est invalide."
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
	 * @Assert\Url(
     *     message = "L’adresse URL {{ value }} est invalide."
     * )
     */
    private $website;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="structures")
     */
    private $user;

    public function __construct()
    {
        $this->updateAt = new \DateTime();
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->updateAt;
    }

    public function setUpdateAt(\DateTimeInterface $updateAt): self
    {
        $this->updateAt = $updateAt;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrganizationType(): ?string
    {
        return $this->organization_type;
    }

    public function setOrganizationType(string $organization_type): self
    {
        $this->organization_type = $organization_type;

        return $this;
    }

    public function getSchoolType(): ?string
    {
        return $this->school_type;
    }

    public function setSchoolType(?string $school_type): self
    {
        $this->school_type = $school_type;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $logoFile
     */
    public function setLogoFile(?File $logoFile = null): void
    {
        $this->logoFile = $logoFile;

        if (null !== $logoFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getLogoFile(): ?File
    {
        return $this->logoFile;
    }

    public function setLogoName(?string $logoName): void
    {
        $this->logoName = $logoName;
    }

    public function getLogoName(): ?string
    {
        return $this->logoName;
    }

    public function getSummar(): ?string
    {
        return $this->summar;
    }

    public function setSummar(?string $summar): self
    {
        $this->summar = $summar;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPostaladdress(): ?string
    {
        return $this->postaladdress;
    }

    public function setPostaladdress(?string $postaladdress): self
    {
        $this->postaladdress = $postaladdress;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/StructureType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Structure;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class StructureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $structure = strtolower($options['structure']);
		$builder
            ->add('name', TextType::class, [
                'label' => 'Nom',
                'attr' => [
                    'required' => true,
                    'placeholder' => 'Entrez le nom',
                ],
            ]);
			
			if ($structure == "etablissement scolaire") {
			$builder
			->add('school_type', ChoiceType::class, [
                'label' => 'Sélectionnez le type d\'établissement scolaire',
                'expanded' => true,
                'choices' => [
                    'Ecole maternelle' => 'Ecole maternelle',
                    'Ecole primaire' => 'Ecole primaire',
                    'Collège' => 'Collège',
					'Lycée' => 'Lycée',
                ],
            ]);
			}
			
           $builder
            ->add('summar', TextareaType::class, [
                'label' => 'Quelques mots sur l\'infrastructure',
                'attr' => [
                    'placeholder' => 'Quelques mots sur l\'infrastructure',
                ],
            ])
            ->add('content', TextareaType::class, [
                'label' => 'Description',
                'attr' => [
                    'placeholder' => 'Indiqur une description',
                ],
            ])
            ->add('postaladdress', TextType::class, [
                'label' => 'Adresse postale',
                'attr' => [
                    'placeholder' => 'Entrez l\'adresse postale',
                ],
            ])
            ->add('phone', TelType::class, [
                'label' => 'Numéro de téléphone',
                'attr' => [
                    'placeholder' => 'Entrez le numéro de téléphone',
                ],
            ])
            ->add('email', EmailType::class, [
                'label' => 'Adresse email',
                'attr' => [
                    'placeholder' => 'Entrez l\adrsse email',
                ],
            ])
            ->add('website', UrlType::class, [
                'label' => 'Adresse URL',
                'attr' => [
                    'placeholder' => 'Entrez l\'adresse URL',
                ],
            ])
            ->add('logoFile', VichImageType::class, array(
			'label' => 'Importez un logo',
                'required' => false,
                'attr' => [
                    'placeholder' => 'Logo de la structure',
                ],
                'allow_delete' => false,
                'download_uri' => false
            ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Structure::class,
			'structure' => null,
        ]);
    }
}

src/Controller/StructureController.php
<?php

    namespace App\Controller;

use App\Entity\User;
use App\Entity\Structure;
use App\Form\StructureType;
use App\Repository\StructureRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;

class StructureController extends AbstractController
{

    /**
     * @Route("/user/{structure}/index", name="structure_index")
	 * @Route("/{structure}/index", name="structure_indexpublic")
	 * @param $_route
     */
    public function structure_index($_route, $structure)
    {
        $structures = $this->getDoctrine()->getRepository(Structure::class)->findBy(['organization_type' => $structure]);
        
		$render = $_route=="structure_index" ? 'structure/index.html.twig' : 'structure/indexpublic.html.twig';
		return $this->render($render, [
            'structures' => $structures,
			'structure' => $structure,
        ]);
    }

    /**
     * @Route("/user/{structure}/new", name="structure_new")
     */
    public function structure_new($structure, Request $request)
    {
        $infrastructure = new Structure();
        $form = $this->createForm(StructureType::class, $infrastructure, [
            'structure' => $structure,
        ]);
        $form->handleRequest($request);
        $user =  $this->getUser();

        if ($form->isSubmitted() && $form->isValid()) {
			$infrastructure->setOrganizationType($structure);
            $infrastructure->setCreatedAt(new \DateTime('now', new \DateTimeZone('Europe/Paris')));
            $infrastructure->setUser($user);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($infrastructure);
            $entityManager->flush();

            return $this->redirectToRoute('structure_index', ['structure' => $infrastructure->getOrganizationType() ]);
        }

        return $this->render('structure/new.html.twig', [
            'structure' => $structure,
			'infrastructure' => $infrastructure,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/user/structure/show/{id}", name="structure_show")
	 * @Route("/structure/show/{id}", name="structure_showpublic")
	 * @param $_route
     */
    public function structure_show($_route, $id, Structure $infrastructure, EntityManagerInterface $manager)
    {
        $user = $infrastructure->getUser();
        $firstname = $user->getFirstname();
        $lastname = $user->getLastname();
        $fullname = $firstname." ".$lastname;
        $infrastructure = $manager->getRepository(Structure::class)->find($id);
		$render = $_route=="structure_show" ? 'structure/show.html.twig' : 'structure/showpublic.html.twig';
		return $this->render($render, [
            'infrastructure' => $infrastructure,
			'id' => $id,
            'structure' => $infrastructure->getOrganizationType(),
            'fullname' => $fullname,
        ]);
    }

    /**
     * @Route("/user/{structure}/show/{id}", name="structure_show")
	 * @Route("/{structure}/show/{id}", name="structure_showpublic")
	 * @param $_route
     */
    /*
    public function structure_show($id, Structure $infrastructure, EntityManagerInterface $manager, Request $request)
    {
        $currentRoute = $request->attributes->get('_route');
        $infrastructure = $manager->getRepository(Structure::class)->find($id);
        if($currentRoute == "structure_show") {
            $route = "structure_show";
        } else if ($currentRoute == "structure_showpublic"){
            $route = "structure_showpublic";
        }
        $html = ".html.twig";
        return $this->render($route.$html, [
            'infrastructure' => $infrastructure,
            'id' => $id,
        ]);
    }
    */

    /**
     * @Route("/user/structure/edit/{id}", name="structure_edit")
     */
    public function structure_edit(Request $request, Structure $infrastructure): Response
    {
        $structure = $infrastructure->getOrganizationType();
		$form = $this->createForm(StructureType::class, $infrastructure, [
            'structure' => $structure,
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
			$infrastructure->setOrganizationType($structure);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('structure_index', ['structure' => $infrastructure->getOrganizationType() ]);
        }

        return $this->render('structure/edit.html.twig', [
            'structure' => $structure,
			'infrastructure' => $infrastructure,
            'form' => $form->createView(),
        ]);
    }
	
    /**
     * @Route("/user/structure/delete/{id}", name="structure_delete")
     */
		public function structure_delete($id, Request $request, EntityManagerInterface $manager)
    {
        $infrastructure = $manager->getRepository(Structure::class)->find($id);
		$structure = $infrastructure->getOrganizationType();
        $manager->remove($infrastructure);
        $manager->flush();
        return $this->redirectToRoute('structure_index', [ 'structure' => $structure ]);
    }

}

templates/structure/_delete_form.html.twig
<form method="post" action="{{ path('structure_delete', {'id': infrastructure.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ infrastructure.id) }}">
    <button class="btn btn-delete">Supprimer</button>
</form>

templates/structure/_delete_form_index.html.twig
<form method="post" action="{{ path('structure_delete', {'id': structure.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ structure.id) }}">
    <button class="btn btn-delete">Supprimer</button>
</form>

templates/structure/_form.html.twig
<div class="mt-5">
    {{ form_start(form) }}

        <div class="form-outline mb-4">
            {{ form_label(form.name) }}
            {{ form_widget(form.name, {'attr': {'class': 'form-control'}}) }}
        </div>

        <div class="row mb-4">
            <div class="col">
                <div class="form-outline mb-4">
                {#
                    {{ form_label(form.logoName) }}</br>
                    {{ form_widget(form.logoName, {'attr': {'class': 'form-control'}}) }}
                    #}
                </div>
            </div>
            <div class="col">
                <div class="form-outline mb-4">
                    {{ form_label(form.logoFile) }}</br>
                    {{ form_widget(form.logoFile) }}
                </div>
            </div>
        </div>
		{% if form.school_type is defined %}
		<div class="form-outline mb-4">
            {{ form_label(form.school_type) }}
            {{ form_widget(form.school_type, {'attr': {'class': 'form-control'}}) }}
        </div>
		{% endif %}

        <div class="form-outline mb-4">
            {{ form_label(form.summar) }}
            {{ form_widget(form.summar, {'attr': {'class': 'form-control'}}) }}
        </div>

        <div class="form-outline mb-4">
            {{ form_label(form.content) }}
            {{ form_widget(form.content, {'attr': {'class': 'form-control'}}) }}
        </div>

        <div class="row mb-4">
            <div class="col">
                <div class="form-outline mb-4">
                    {{ form_label(form.postaladdress) }}
                    {{ form_widget(form.postaladdress, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            <div class="col">
                <div class="form-outline mb-4">
                    {{ form_label(form.phone) }}
                    {{ form_widget(form.phone, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
        </div>

        <div class="row mb-4">
            <div class="col">
                <div class="form-outline mb-4">
                    {{ form_label(form.email) }}
                    {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            <div class="col">
                <div class="form-outline mb-4">
                    {{ form_label(form.website) }}
                    {{ form_widget(form.website, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
        </div>

        <div class="form-outline mb-4">{#
            {{ form_label(form.user) }}
            {{ form_widget(form.user, {'attr': {'class': 'form-control'}}) }}#}
        </div>

        <div class="justify-content-end">
            <button class="btn btn-secondary">{{ infrastructure.id ? 'Modifier' : 'Créer' }}</button>
        </div>
    {{ form_end(form) }}
</div>

templates/structure/edit.html.twig
{% extends 'admin/base.html.twig' %}

{% block title %}Modification «{{ structure }}»{% endblock %}

{% block body %}
    <section>
        <a href="{{ path('structure_index', {'structure': infrastructure.organizationType}) }}" class="btn btn-delete mx-3 my-3" role="button" aria-pressed="true">Retour</a>

        <div class="container">
            <div class="text-center">
                <h1>Modifier la structure</h1>
            </div>

            {{ include('structure/_form.html.twig') }}
        </div>
    </section>
{% endblock %}

templates/structure/index.html.twig
{% extends 'admin/base.html.twig' %}

{% block title %}Gestion des {{ structure }}s{% endblock %}

{% block body %}
    <div class="container-fluid mt-5">
        <div class="text-center">
            <h1>Structure <strong>{{ structure }}</strong></h1>
        </div>

        <div class="d-flex mt-5 justify-content-center justify-content-md-start">
            <a href="{{ path('structure_new', {'structure': structure}) }}" class="btn btn-secondary" role="button" aria-pressed="true">Ajouter <strong>{{ structure }}</strong></a>
        </div>

        <div class="mt-5 d-none d-md-block">
            <table class="table">
                <thead>
                    <tr class="text-center">
                        <th>Nom</th>
                        <th>Adresse</th>
                        <th>Téléphone</th>
                        <th>Email</th>
                        <th>Site internet</th>
                        <th>Créée le </th>
                        <th>Auteur</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for structure in structures %}
                    <tr class="text-center">
                        <td>{{ structure.schoolType }} {{ structure.name }}</td>
                        <td>{{ structure.postaladdress }}</td>
                        <td>{{ structure.phone }}</td>
                        <td>{{ structure.email }}</td>
                        <td>{{ structure.website }}</td>
                        <td>{{ structure.createdat ? structure.createdat|date('d/m/Y à H:i') : '' }}</td>
                        <td>{{ structure.user.firstname }} {{ structure.user.lastname }}</td>
                        <td class="d-flex justify-content-center">
                            <a href="{{ path('structure_show', {'id': structure.id}) }}" class="btn btn-see mr-2" role="button" aria-pressed="true">Voir</a>
                            <a href="{{ path('structure_edit', {'id': structure.id}) }}" class="btn btn-secondary mr-2" role="button" aria-pressed="true">Modifier</a>
                            {{ include('structure/_delete_form_index.html.twig') }}
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="13">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="d-block d-sm-none mt-5">
            <table class="table">
                <thead>
                    <tr class="text-center">
                        <th>Nom des structures</th>
                    </tr>
                </thead>
                <tbody>
                {% for structure in structures %}
                    <tr>
                        <td>
                            <a href="{{ path('structure_show', {'id': structure.id}) }}">{{ structure.name }}</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="9">Aucune structure enregistrée.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/structure/indexpublic.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{% if structure == "etablissement scolaire" %}
		Nos établissements scolaires
	{% else %}
        Nos {{ structure }}s
	{% endif %}
{% endblock %}

{% block body %}
    <div class="container-fluid">
        {% if structure is same as "etablissement scolaire" %}
            <div class="text-center">
                <h1 style="color:#bc4464;">Nos établissements scolaires</h1>
            </div>
        {% else %}
            <div class="text-center">
                <h1 style="color:#bc4464;">Nos {{ structure }}s</h1>
            </div>
        {% endif %}
            {% for structure in structures %}
                <div class="d-flex justify-content-center mt-3">
                    <div class="card w-75 mb-3 blog-main shadow p-3 mb-5 bg-white rounded">
                        <div class="card-body">
                            <h5 class="card-title" style="color:#4464bc;">{{ structure.schoolType }} {{ structure.name }}</h5>
                            <p class="card-text">{{ structure.summar }}</p>
                            <div class="d-flex justify-content-end">
                                <a href="{{ path('structure_showpublic', {'structure': structure.organizationType, 'id': structure.id }) }}" class="btn btn-see">En savoir plus</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
    </div>
{% endblock %}

templates/structure/new.html.twig
{% extends 'admin/base.html.twig' %}

{% block title %}Création «{{ structure }}»{% endblock %}

{% block body %}
    <section>
        <a href="{{ path('structure_index', {'structure': structure}) }}" class="btn btn-delete mx-3 my-3" role="button" aria-pressed="true">Retour</a>

        <div class="container">
            <div class="text-center">
                <h1>Création d'une structure</h1>
            </div>

            {{ include('structure/_form.html.twig') }}
        </div>
    </section>
{% endblock %}

templates/structure/show.html.twig
{% extends 'admin/base.html.twig' %}

{% block title %}{{ infrastructure.organizationType }} {{ infrastructure.name }}{% endblock %}

{% block body %}
    <section>
        <a href="{{ path('structure_index', {'structure': infrastructure.organizationType}) }}" class="btn btn-delete mx-3 my-3" role="button" aria-pressed="true">Retour</a>
        
        <div class="container">
            <div class="text-center">
                <h1>{{ infrastructure.schoolType }} {{ infrastructure.name }}</h1>
            </div>

            <div class="mt-5">
                <table class="table">
                    <tbody>
                        <tr>
                            <th>Logo</th>
                            <td><img src="{{ vich_uploader_asset(infrastructure, 'logoFile') }}" width="150"/></td>
                        </tr>
                        <tr>
                            <th>Résumé</th>
                            <td>{{ infrastructure.summar }}</td>
                        </tr>
                        <tr>
                            <th>Contenu</th>
                            <td>{{ infrastructure.content }}</td>
                        </tr>
                        <tr>
                            <th>Adresse</th>
                            <td>{{ infrastructure.postaladdress }}</td>
                        </tr>
                        <tr>
                            <th>Numéro de téléphone</th>
                            <td>{{ infrastructure.phone }}</td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td>{{ infrastructure.email }}</td>
                        </tr>
                        <tr>
                            <th>Site internet</th>
                            <td>{{ infrastructure.website }}</td>
                        </tr>
                        <tr>
                            <th>Créée le</th>
                            <td>{{ infrastructure.createdat ? infrastructure.createdat|date('d/m/Y à H:i') : '' }}</td>
                        </tr>
                        <tr>
                            <th>Edité par</th>
                            <td><p>{{ fullname }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="d-flex justify-content-end mb-2">
                <a href="{{ path('structure_edit', {'id': infrastructure.id}) }}" class="btn btn-secondary mr-2" role="button" aria-pressed="true">Modifier</a>
                {{ include('structure/_delete_form.html.twig') }}
            </div>
        </div>
    </section>
{% endblock %}

templates/structure/showpublic.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ infrastructure.name }}{% endblock %}

{% block body %}

<div class="container-fluid">
	<div class="jumbotron text-center" style="background-color:#bc4464;">
		<h4 class="card-title h4 pb-2"><strong>{{ infrastructure.name }}</strong></h4>

		{% if infrastructure.organizationType is same as "Etablissement scolaire" %}
			<h6>{{ infrastructure.schoolType }}</h6>
		{% endif %}

		{% if infrastructure.logoName is not null %}
			<div class="view overlay my-4">
				<img class="img-fluid" src="{{ vich_uploader_asset(infrastructure, 'logoFile') }}" alt="photo du logo"/>
			</div>
		{% else %}
			<div class="view overlay my-4">
				{#<img class="img-fluid" src="{{ asset('images/building-1089861_1920.jpg') }}" alt="photo du logo"/>#}
			</div>
		{% endif %}

		{% if infrastructure.summar is not null %}
			<h5 class="indigo-text h5 mb-4">{{ infrastructure.summar }}</h5>
		{% endif %}

		{% if infrastructure.content is not null %}
			<p class="card-text">{{ infrastructure.content }}</p>
		{% endif %}
		
		<div class="d-md-flex ml-3 ml-md-0">
			<div class="col-md-3">
				{% if infrastructure.postaladdress is not null %}
					<div class="card" style="width: 18rem; background-color:#E8ECF7;">
						<div class="card-body">
							<h6 class="card-subtitle mb-2" style="color:#4464bc;">Adresse postale</h6>
							<p class="card-text">{{ infrastructure.postaladdress }}</p>
						</div>
					</div>
				{% endif %}
			</div>
			<div class="col-md-3 mt-3 mt-md-0">
				{% if infrastructure.phone is not null %}
					<div class="card" style="width: 18rem;background-color:#E8ECF7;">
						<div class="card-body">
							<h6 class="card-subtitle mb-2" style="color:#4464bc;">Numéro de téléphone</h6>
							<p class="card-text">{{ infrastructure.phone }}</p>
						</div>
					</div>
				{% endif %}
			</div>
			<div class="col-md-3 mt-3 mt-md-0">
				{% if infrastructure.email is not null %}
					<div class="card" style="width: 18rem;background-color:#E8ECF7;">
						<div class="card-body">
							<h6 class="card-subtitle mb-2" style="color:#4464bc;">Adresse email</h6>
							<p class="card-text">{{ infrastructure.email }}</p>
						</div>
					</div>
				{% endif %}
			</div>
			<div class="col-md-3 mt-3 mt-md-0">
				{% if infrastructure.website is not null %}
					<div class="card" style="width: 18rem;background-color:#E8ECF7;">
						<div class="card-body">
							<h6 class="card-subtitle mb-2" style="color:#4464bc;">Site internet</h6>
							<p class="card-text">{{ infrastructure.website }}</p>
						</div>
					</div>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}